run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: demo_FSM
        subdir: test
gpt: 
    model: 4t
autoline: 
    probset:
        name: HDLBits
        path: data/HDLBits/HDLBits_data.jsonl
        mutant_path: data/HDLBits/HDLBits_data_mutants.jsonl
        only: ["fsm3"]
    promptscript: pychecker
    timeout: 40